"""small changes

Revision ID: 324b431fdeb4
Revises: 3ded26d5450c
Create Date: 2024-11-14 17:59:43.359905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "324b431fdeb4"
down_revision: Union[str, None] = "3ded26d5450c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses",
        "expense_date",
        existing_type=sa.DATE(),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "expenses",
        "due_date",
        existing_type=sa.DATE(),
        type_=sa.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "payments",
        "payment_date",
        existing_type=sa.DATE(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "payments",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "payments",
        "status",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "payments",
        "payment_date",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DATE(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "expenses",
        "due_date",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.alter_column(
        "expenses",
        "expense_date",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DATE(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
