"""check changes

Revision ID: 3ded26d5450c
Revises: c5930bc73865
Create Date: 2024-11-13 21:45:45.449071

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "3ded26d5450c"
down_revision: Union[str, None] = "c5930bc73865"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
