"""initial migration

Revision ID: c5930bc73865
Revises:
Create Date: 2024-11-13 21:28:28.478550

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c5930bc73865"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
